import type { Metadata } from 'next';
import { Lato, Courgette } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import { AuthProvider } from '@/contexts/AuthContext';

// Font setup
// Lato is the default font
const lato = Lato({ weight: '400', subsets: ['latin'] });
// fontTitle uses the Courgette font, and it can be used in different components as an import
const courgette = Courgette({ weight: '400', subsets: ['latin'] });
export const fontTitle = courgette.className;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
